name: Lambda python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
    - uses: action/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m piüp install --upgrade pip
        pip install -r ../test/requirements.txt
    - name: Test with pytest
      run: |
        pytest ../test/test_counter_function.py --doctest-modules --cov-report=html
