name: static-website-update-s3

on:
  push:
    paths:
      - 'app_template/**'

env:
  AWS_REGION: eu-central-1


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: upload to s3 bucket
        working-directory: ./app_template
        run: aws s3 sync index.html s3://resume.collinsunaichi.co.uk
        run: aws s3 sync style.css s3://resume.collinsunaichi.co.uk

      - name: update image in s3
        run: aws s3 sync ./image s3://resume.collinsunaichi.co.uk
      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"